name: Build Millennium (Linux)

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install pyenv dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make build-essential libssl-dev zlib1g-dev \
            libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
            libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev \
            git

    - name: Install pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV

    - name: Reload environment
      shell: bash
      run: |
        source $GITHUB_ENV
        pyenv update

    - name: Install Python 3.11.8
      run: |
        pyenv install 3.11.8
        pyenv global 3.11.8

    - name: Verify Python version
      run: python --version

    - name: (Generator) Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.21.1'
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: (Dependency) Install vcpkg & setup environment
      run: |

        sudo apt install libgtk-3-dev

        # bootstrap and install vcpkg
        ./vendor/vcpkg/bootstrap-vcpkg.sh
        ./vendor/vcpkg/vcpkg integrate install
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: (Generator) Configure CMake
      run: |
        cmake --preset=linux -G "Unix Makefiles" -DGITHUB_ACTION_BUILD=ON
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Build Millennium
      run: |

        mkdir ./build/artifacts
        cmake --build build
        ldd ./build/user32
        cp ./build/user32 ./build/artifacts/user32
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: millennium
        path: ./build/artifacts